package com.example;

/**
 * Simple calculator used for demonstration and tests generated by AI.
 */
public class Calculator {

    public int add(int a, int b) {
        return a + b;
    }

    public int divide(int a, int b) {
        return a / b; // will throw ArithmeticException when b == 0
    }
}
