version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: pg-outbox
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: outbox_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-outbox
    restart: always
    ports:
      - "5672:5672"     # Broker AMQP
      - "15672:15672"   # UI Web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  pgdata:
